version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ha-config:/config
    restart: always
    privileged: true
    network_mode: host
volumes:
 ha-config: {}