version: '2'
services:
  homeassistant:
    build: homeassistant
    depends_on:
      - mqtt
      - nodered
    volumes:
      - ha-config:/config
    restart: always
    privileged: true
    network_mode: host
    ports: 
      - 80:8123
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - mqtt-data:/mosquitto
    networks:
      - backend
    ports:
      - 1883:1883
  nodered:
    depends_on:
      - mqtt
    build: nodered
    volumes:
      - node-red-data:/data
    user: 1000:1000
    networks:
      - backend
    ports:
      - 1880:1880
networks:
  backend:
volumes:
 ha-config: {}
 node-red-data: {}
 mqtt-data: {}